//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Commercial_Company_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Cust_ID { get; set; }
        public string Cust_Name { get; set; }
        public int Cust_Mobile { get; set; }
        public Nullable<int> Cust_Telephone { get; set; }
        public Nullable<int> Cust_Fax { get; set; }
        public string Cust_Email { get; set; }
        public string Cust_Website { get; set; }
    }
}
