//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Commercial_Company_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measurement
    {
        public int Measure_ID { get; set; }
        public string Measure_Name { get; set; }
        public int Item_Code { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
