//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Commercial_Company_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Permission()
        {
            this.Permissioned_Item = new HashSet<Permissioned_Item>();
        }
    
        public int Permission_ID { get; set; }
        public System.DateTime Permission_Date { get; set; }
        public int Permission_Type { get; set; }
        public int Store_ID { get; set; }
        public int Supp_ID { get; set; }
    
        public virtual Store Store { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Permissioned_Item> Permissioned_Item { get; set; }
    }
}
