//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Commercial_Company_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transfer_Item
    {
        public int Trans_ID { get; set; }
        public Nullable<int> From_ID { get; set; }
        public Nullable<int> To_ID { get; set; }
        public Nullable<int> Supp_ID { get; set; }
        public Nullable<int> Item_Code { get; set; }
        public Nullable<int> Item_Total { get; set; }
        public Nullable<System.DateTime> Production_Date { get; set; }
        public Nullable<System.DateTime> Expiration_Date { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Store Store { get; set; }
        public virtual Store Store1 { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
